### ISSUE TITLE
Faster hermf function is failing to match values in Xiao and Flandrin's matlab code for some python versions

### ISSUE THREAD

**Issue by dmeliza** [melizalab/libtfr#17]
Pull request #16 is generating errors for some python versions (3.6, possibly others) in the `test_hermf` test, which compares the output of the hermf function with values I copied over from the Xiao and Flandrin implementation (http://perso.ens-lyon.fr/patrick.flandrin/hermf.m)

These might be small rounding errors, but the test doesn't currently print out the actual values so this needs further investigation.

**Comment by xyzzy42** [comment]
So I tested this manually to check the differences, and they are very small, less than the 1e-15 to which the expected values are specified to.  And I wrote a response with all the numbers.

But then I checked `np.allclose()`, and it has a much looser limit, 1e-8, so it should be passing just fine....

Anyway, a little test with valgrind told me there was an uninitialized memory bug.  It wasn't hard to spot. Pkm2 isn't initialized to zero for the first iteration, when k=1.  It was just luck that all the tests I ran happened to have the memory already zero and produced the correct values.

Test data, since I went to the trouble of formatting it already.

h
```
Expected             Actual                 |E-A|
0.038241135791969    0.03824113579196922    2.220446049250313e-16
0.0                  0.0                    0.0
0.027040563146761    0.0270405631467606     3.9898639947466563e-16
0.0                  1.1046995269902055e-18 1.1046995269902055e-18
0.023417748319781    0.02341774831978106    6.245004513516506e-17
-0.0                 0.0                    0.0
```

Dh²
```
Expected             Actual                 |E-A|
0.0018               0.0017999999999999978  2.168404344971009e-18
0.0054               0.00539999999999986    1.4051260155412137e-16
0.008999999999995    0.0089999999999952     1.9949319973733282e-16
0.012599999999893    0.012599999999893217   2.1684043449710089e-16
0.016199999998273    0.016199999998273255   2.5673907444456745e-16
0.0197999999784      0.019799999978399832   1.6653345369377348e-16
```
