### ISSUE TITLE
how to properly calculating the inverse transform of libtfr.tfr_spec

### ISSUE THREAD

**Issue by ysig** [melizalab/libtfr#8]
Hi,

I am using:

`reassigned_stft = libtfr.tfr_spec(s=sig, N=nfft, step=shift, Np=Np, K=K, tm=tm, flock=flock, tlock=tlock)`

for an application, where I decompose the signal in spectrograms apply some transformations and recompose it back again.
I used you implementation with istft from librosa, as:

`librosa.istft(reassigned_stft , hop_length=shift, win_length=Np)`

to invert my signal and it produces a very noisy, loud and bad sounding signal.
Do you support an available process for inverting tfr_spec?

PS: Also I noticed that tfr_spec, didn't produce the same result on different runs of my algorithm.
I am running this on Google Collab.

**Comment by dmeliza** [comment]
Although my signal-processing theory is limited, I doubt that this will work. You can invert an STFT even with only the amplitude (i.e. discarding the phase) because the spectral bands overlap sufficiently to recover the fine structure of the signal. The reassignment process explicitly disrupts the spectrotemporal distribution of power to enhance the appearance of the spectrogram, so I suspect it will not help you recover the original signal.

**Comment by dmeliza** [comment]
Closing as not addressable.
